language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - jruby-19mode
  - ruby-head
  - jruby-head
gemfile:
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
notifications:
  email:
    - agresso@gmail.com
branches:
  only:
    - master
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
